"""
Core enums for the claims processing pipeline.

Why enums? In a financial/insurance system, stringly-typed values are a bug factory.
If Agent 1 produces "approved" and Agent 2 checks decision == "APPROVED", the system
silently fails. Enums make mismatches loud (AttributeError, not silent wrong result).

All enums inherit from (str, Enum) so they JSON-serialize to their string value.
This keeps the API contract clean: clients see "APPROVED", not "DecisionType.APPROVED".
"""

from __future__ import annotations

from enum import Enum


class _StrEnum(str, Enum):
    """Base class so all enums serialize to plain strings in JSON."""
    pass


# ----------------------------- Document domain -----------------------------

class DocumentType(_StrEnum):
    """All document types the system recognizes."""
    PRESCRIPTION = "PRESCRIPTION"
    HOSPITAL_BILL = "HOSPITAL_BILL"
    PHARMACY_BILL = "PHARMACY_BILL"
    LAB_REPORT = "LAB_REPORT"
    DIAGNOSTIC_REPORT = "DIAGNOSTIC_REPORT"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    DENTAL_REPORT = "DENTAL_REPORT"
    UNKNOWN = "UNKNOWN"


class DocumentQuality(_StrEnum):
    """Quality assessment of an uploaded document.

    GOOD         - readable, high quality
    POOR         - readable but degraded (low contrast, slight blur)
    UNREADABLE   - cannot be parsed (heavy blur, cut off, etc.)
    """
    GOOD = "GOOD"
    POOR = "POOR"
    UNREADABLE = "UNREADABLE"


# ----------------------------- Claim domain -----------------------------

class ClaimCategory(_StrEnum):
    """OPD claim categories defined in policy_terms.json.

    Each category has its own sub-limit, co-pay, network discount, and document
    requirements. Adding a new category requires updating policy_terms.json
    AND document_requirements in that file — no code change needed.
    """
    CONSULTATION = "CONSULTATION"
    DIAGNOSTIC = "DIAGNOSTIC"
    PHARMACY = "PHARMACY"
    DENTAL = "DENTAL"
    VISION = "VISION"
    ALTERNATIVE_MEDICINE = "ALTERNATIVE_MEDICINE"


class Relationship(_StrEnum):
    SELF = "SELF"
    SPOUSE = "SPOUSE"
    CHILD = "CHILD"
    CHILDREN = "CHILDREN"
    PARENT = "PARENT"
    PARENTS = "PARENTS"


# ----------------------------- Decision domain -----------------------------

class DecisionType(_StrEnum):
    """The four possible claim decisions. These are the system's outputs."""
    APPROVED = "APPROVED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class RejectionReason(_StrEnum):
    """Specific reasons a claim (or line item) can be rejected.

    Each reason maps to a policy rule. The system can produce multiple
    reasons for a single claim (e.g. waiting period AND excluded condition).
    """
    WAITING_PERIOD = "WAITING_PERIOD"
    EXCLUDED_CONDITION = "EXCLUDED_CONDITION"
    PRE_AUTH_MISSING = "PRE_AUTH_MISSING"
    PER_CLAIM_EXCEEDED = "PER_CLAIM_EXCEEDED"
    NOT_COVERED = "NOT_COVERED"
    MEMBER_INELIGIBLE = "MEMBER_INELIGIBLE"
    SUB_LIMIT_EXCEEDED = "SUB_LIMIT_EXCEEDED"
    OUTSIDE_NETWORK = "OUTSIDE_NETWORK"
    DOCUMENT_FRAUD = "DOCUMENT_FRAUD"
    HIGH_FRAUD_SCORE = "HIGH_FRAUD_SCORE"


class DocumentError(_StrEnum):
    """Errors raised by the DocumentVerification agent.

    These all cause the system to STOP before any decision is made.
    The user-facing message is generated by the agent based on the error.
    """
    MISSING_REQUIRED_DOCUMENT = "MISSING_REQUIRED_DOCUMENT"
    WRONG_DOCUMENT_TYPE = "WRONG_DOCUMENT_TYPE"
    UNREADABLE_DOCUMENT = "UNREADABLE_DOCUMENT"
    PATIENT_NAME_MISMATCH = "PATIENT_NAME_MISMATCH"
    LOW_QUALITY_DOCUMENT = "LOW_QUALITY_DOCUMENT"
    DUPLICATE_DOCUMENT = "DUPLICATE_DOCUMENT"


class FraudSignal(_StrEnum):
    """Signals that may indicate fraudulent activity."""
    SAME_DAY_LIMIT_EXCEEDED = "SAME_DAY_LIMIT_EXCEEDED"
    MONTHLY_LIMIT_EXCEEDED = "MONTHLY_LIMIT_EXCEEDED"
    HIGH_VALUE_CLAIM = "HIGH_VALUE_CLAIM"
    DOCUMENT_ALTERATION = "DOCUMENT_ALTERATION"
    SUSPECTED_FAKE_DOCUMENT = "SUSPECTED_FAKE_DOCUMENT"


# ----------------------------- Agent domain -----------------------------

class AgentStatus(_StrEnum):
    """Status of an individual agent run within the trace."""
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    PARTIAL = "PARTIAL"


class AgentName(_StrEnum):
    """The 6 agents in our pipeline + the orchestrator.

    Used in the trace so reviewers can grep for "DocumentVerification" etc.
    """
    DOCUMENT_VERIFICATION = "DocumentVerification"
    DOCUMENT_EXTRACTION = "DocumentExtraction"
    MEMBER_VALIDATION = "MemberValidation"
    POLICY_RULES = "PolicyRules"
    FRAUD_DETECTION = "FraudDetection"
    DECISION = "Decision"
    ORCHESTRATOR = "Orchestrator"


# ----------------------------- Failure simulation -----------------------------

class ComponentFailure(_StrEnum):
    """For TC011 — which simulated component should fail.

    Set in ClaimInput.simulate_component_failure; the orchestrator injects
    a failure into the named agent to test graceful degradation.
    """
    DOCUMENT_EXTRACTION = "DOCUMENT_EXTRACTION"
    FRAUD_DETECTION = "FRAUD_DETECTION"
    MEMBER_VALIDATION = "MEMBER_VALIDATION"
    POLICY_RULES = "POLICY_RULES"
